
FROM node

RUN apt-get update
RUN apt-get install -y wget unzip git cron vim nginx \
    && npm install -g pm2 \
    && mkdir /Sub-Store

ENV TZ=Asia/Shanghai

ENV Sourcepath="https://github.com/dompling/Sub-Store.git"
ENV DMIAN="/"

COPY /Sub-Store/nginx/* /etc/nginx/config.d

WORKDIR /Sub-Store

RUN git clone ${Sourcepath} /Sub-Store \
     && cd /Sub-Store/backend \
     && npm install \
     && cd /Sub-Store/web \
     && npm install \
     && npm run build \
     && nginx -c /etc/nginx/nginx.conf \
     && nginx -s reload

CMD cd /Sub-Store/backend && pm2 start sub-store.js && cron -f




