
FROM node:14-alpine

RUN apk update
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates \
    curl \
    tzdata \
    git \
    nodejs \
    npm \
    nginx\
    gettext\
    && mkdir /git \
    && mkdir /Sub-Store \
    && mkdir /Sub-Store/nginx \
    && npm install -g cnpm pm2



ENV GIT="https://github.com/dompling/Sub-Store.git"
ENV DOMAIN="/"
ENV Authorization=""
ENV TZ=Asia/Shanghai

WORKDIR /Sub-Store

RUN git clone ${GIT} /git\
    && cd /git/backend \
    && cp -r /git/web /Sub-Store/ \
    && cp -r /git/backend /Sub-Store/ \
    && cd /git/backend \
    && cnpm install \
    && cd /git/web \
    && cnpm install \ 
    && mkdir -p /etc/nginx/conf.d \
    && cp -r /git/nginx/front* /etc/nginx/conf.d/ \
    && cp -r /git/nginx/nginx.conf /etc/nginx/

RUN chmod 777 /git/docker/sub-store.sh

ENTRYPOINT ["/bin/sh","/git/docker/sub-store.sh" ]