
FROM alpine

RUN apk update
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates \
    curl \
    tzdata \
    git \
    nodejs \
    npm \
    nginx\
    gettext\
    && mkdir /git \
    && mkdir /docker \
    && mkdir /Sub-Store \
    && mkdir /Sub-Store/nginx \
    && npm install -g cnpm pm2

COPY /Sub-Store/sub-store.sh /Sub-Store/
COPY /Sub-Store/nginx/nginx.conf /etc/nginx/
COPY /Sub-Store/nginx/front.conf /Sub-Store/nginx/
COPY /Sub-Store/nginx/front.template /Sub-Store/nginx/

RUN chmod +x /Sub-Store/sub-store.sh

ENV GIT="https://github.com/Peng-YM/Sub-Store.git"
ENV DOMAIN="/"
ENV ALLOW_IP=""

WORKDIR /Sub-Store

RUN git clone ${GIT} /git\
    && cd /git/backend \
    && cp -r /git/web /Sub-Store/ \
    && cp -r /git/backend /Sub-Store/ \
    && cd /Sub-Store/backend \
    && cnpm install \
    && cd /Sub-Store/web \
    && cnpm install

ENTRYPOINT ["/Sub-Store/sub-store.sh" ]